ANN
CNN
RNN
LSTM
GRU
GENAI

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf

In [2]:
df=pd.read_csv(r'C:\Users\SHIVANSHU SRIVASTAVA\OneDrive\Desktop\ml by upflair\deep learning\cleaned_data.csv')

In [3]:
df.dtypes

price         float64
kms_driven    float64
owner           int64
age             int64
power         float64
brand           int64
dtype: object

In [4]:
df.drop_duplicates(inplace=True)

In [5]:
df.duplicated().sum()

0

In [6]:
df.drop_duplicates(inplace=True)

In [7]:
df.isnull().sum()

price         0
kms_driven    0
owner         0
age           0
power         0
brand         0
dtype: int64

In [8]:
x=df.drop('price',axis=1)
y=df['price']

In [9]:
x

      kms_driven  owner  age  power  brand
0        17654.0      1    3  110.0      8
1        16329.0      1    4  180.0      8
2        10000.0      1    3  150.0      5
3        25000.0      1    6  150.0      5
4         8200.0      1    3  160.0      6
...          ...    ...  ...    ...    ...
4226     10000.0      1    6  180.0      3
4230     41939.0      1    8  200.0      3
4231     29134.0      1    7  220.0      3
4237     60000.0      1    9  220.0      3
4238      7127.0      1    5  220.0      3

[3285 rows x 5 columns]

In [10]:
y

0       35000.0
1       65000.0
2       80000.0
3       53499.0
4       85000.0
         ...
4226    55000.0
4230    48000.0
4231    50000.0
4237    35000.0
4238    80000.0
Name: price, Length: 3285, dtype: float64

In [11]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [12]:
import tensorflow as tf

In [17]:
from tensorflow.keras.layers import Dense, Dropout, Flatten, Conv2D, MaxPooling2D
from tensorflow.keras.models import Sequential

In [18]:
input_shape=(5,)

In [19]:
model=Sequential()

In [20]:
# input layer

model.add(Dense(units=64, activation='relu', input_shape=input_shape))

#dropout layer
model.add(Dropout(0.2))

#hidden layers
model.add(Dense(units=32,activation='relu'))
model.add(Dense(units=16,activation='relu'))
model.add(Dense(units=8,activation='relu'))


#output layer

model.add(Dense(units=1,activation='linear'))


model.compile(optimizer='adam', loss='mean_squared_error', metrics=['mse','mae'])

c:\Users\SHIVANSHU SRIVASTAVA\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [22]:
history=model.fit(x_train,y_train, epochs=10, batch_size=32, validation_split=0.2)

Epoch 1/10

66/66 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 543079872.0000 - mae: 17109.1836 - mse: 543079872.0000 - val_loss: 420922336.0000 - val_mae: 15413.7783 - val_mse: 420922336.0000
Epoch 2/10
66/66 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 530156928.0000 - mae: 16897.0547 - mse: 530156928.0000 - val_loss: 483390400.0000 - val_mae: 16233.5000 - val_mse: 483390400.0000
Epoch 3/10
66/66 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 543673472.0000 - mae: 17384.2676 - mse: 543673472.0000 - val_loss: 417105728.0000 - val_mae: 15685.2695 - val_mse: 417105728.0000
Epoch 4/10
66/66 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 499918368.0000 - mae: 16732.9531 - mse: 499918368.0000 - val_loss: 423465024.0000 - val_mae: 15255.8262 - val_mse: 423465024.0000
Epoch 5/10
66/66 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 528815936.0000 - mae: 16623.2324 - mse: 528815936.0000 - val_loss: 414859840.0000 - val_mae: 15331.0088 - val_mse: 414859840.0000
Epoch 6/10
66/66 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 495241952.0000 - mae: 16644.3965 - mse: 495241952.0000 - val_loss: 411205216.0000 - val_mae: 15132.4463 - val_mse: 411205216.0000
Epoch 7/10
66/66 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 479337888.0000 - mae: 16268.4170 - mse: 479337888.0000 - val_loss: 472899520.0000 - val_mae: 16034.0723 - val_mse: 472899520.0000
Epoch 8/10
66/66 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 511305600.0000 - mae: 16346.1934 - mse: 511305600.0000 - val_loss: 413121600.0000 - val_mae: 15278.6953 - val_mse: 413121600.0000
Epoch 9/10
66/66 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 513537984.0000 - mae: 16803.2871 - mse: 513537984.0000 - val_loss: 416527456.0000 - val_mae: 15090.3252 - val_mse: 416527456.0000
Epoch 10/10
66/66 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 509457152.0000 - mae: 16980.4297 - mse: 509457152.0000 - val_loss: 422147904.0000 - val_mae: 15301.7744 - val_mse: 422147904.0000

In [23]:
pd.DataFrame(history.history)

,loss,mae,mse,val_loss,val_mae,val_mse
0,528193280.0,16981.482422,528193280.0,420922336.0,15413.778320,420922336.0
1,513985600.0,16737.925781,513985600.0,483390400.0,16233.500000,483390400.0
2,522929184.0,16912.851562,522929184.0,417105728.0,15685.269531,417105728.0
3,502303264.0,16604.845703,502303264.0,423465024.0,15255.826172,423465024.0
4,510365856.0,16726.763672,510365856.0,414859840.0,15331.008789,414859840.0
5,506894560.0,16552.728516,506894560.0,411205216.0,15132.446289,411205216.0
6,506782432.0,16656.025391,506782432.0,472899520.0,16034.072266,472899520.0
7,498670944.0,16374.738281,498670944.0,413121600.0,15278.695312,413121600.0
8,497289696.0,16483.632812,497289696.0,416527456.0,15090.325195,416527456.0
9,515237696.0,16858.255859,515237696.0,422147904.0,15301.774414,422147904.0

In [29]:
pred=model.predict(x_test)

21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step

In [30]:
y_test

944      56950.0
232      58000.0
515      45000.0
4072     40000.0
3427    150000.0
          ...
2064     32000.0
48       35000.0
3036     40000.0
2914     57000.0
2806     41000.0
Name: price, Length: 657, dtype: float64

In [31]:
output_data=pd.DataFrame({'actual':y_test.ravel(),'predict':pred.ravel()})

C:\Users\SHIVANSHU SRIVASTAVA\AppData\Local\Temp\ipykernel_11472\1645871915.py:1: FutureWarning: Series.ravel is deprecated. The underlying array is already 1D, so ravel is not necessary.  Use `to_numpy()` for conversion to a numpy array instead.
  output_data=pd.DataFrame({'actual':y_test.ravel(),'predict':pred.ravel()})

In [32]:
output_data

       actual        predict
0     56950.0   35361.445312
1     58000.0   26793.400391
2     45000.0   47123.457031
3     40000.0   38661.808594
4    150000.0  102746.171875
..        ...            ...
652   32000.0   21141.349609
653   35000.0   24750.152344
654   40000.0   62784.906250
655   57000.0   69260.960938
656   41000.0   29839.738281

[657 rows x 2 columns]

In [33]:
output_data.describe()

              actual        predict
count     657.000000     657.000000
mean    52331.184170   49166.257812
std     30879.693386   24172.279297
min      9500.000000   16573.076172
25%     30000.000000   28646.453125
50%     45600.000000   44565.000000
75%     67800.000000   65415.546875
max    160000.000000  140908.687500

In [34]:
model.save('model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.